/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace Client {
  export type EVMTokenAmountStruct = {
    token: AddressLike;
    amount: BigNumberish;
  };

  export type EVMTokenAmountStructOutput = [token: string, amount: bigint] & {
    token: string;
    amount: bigint;
  };

  export type Any2EVMMessageStruct = {
    messageId: BytesLike;
    sourceChainSelector: BigNumberish;
    sender: BytesLike;
    data: BytesLike;
    destTokenAmounts: Client.EVMTokenAmountStruct[];
  };

  export type Any2EVMMessageStructOutput = [
    messageId: string,
    sourceChainSelector: bigint,
    sender: string,
    data: string,
    destTokenAmounts: Client.EVMTokenAmountStructOutput[]
  ] & {
    messageId: string;
    sourceChainSelector: bigint;
    sender: string;
    data: string;
    destTokenAmounts: Client.EVMTokenAmountStructOutput[];
  };
}

export interface BackedCCIPReceiverInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allowlistSender"
      | "allowlistSourceChain"
      | "allowlistedDestinationChains"
      | "allowlistedSenders"
      | "allowlistedSourceChains"
      | "ccipReceive"
      | "custodyWallet"
      | "gasLimit"
      | "getDeliveryFeeCost"
      | "getDeliveryFeeCostWithCustomGasLimit"
      | "getLastReceivedMessageDetails"
      | "getRouter"
      | "initialize"
      | "owner"
      | "registerDestinationChain"
      | "registerToken"
      | "renounceOwnership"
      | "send"
      | "sendWithCustomDestinationGasLimit"
      | "supportsInterface"
      | "tokenIds"
      | "tokens"
      | "transferOwnership"
      | "updateCustodyWallet"
      | "updateGasLimit"
      | "withdraw"
      | "withdrawToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CustodyWalletUpdated"
      | "GasLimitUpdated"
      | "Initialized"
      | "MessageReceived"
      | "MessageSent"
      | "OwnershipTransferred"
      | "TokenRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "allowlistSender",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "allowlistSourceChain",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "allowlistedDestinationChains",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "allowlistedSenders",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "allowlistedSourceChains",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ccipReceive",
    values: [Client.Any2EVMMessageStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "custodyWallet",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "gasLimit", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getDeliveryFeeCost",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDeliveryFeeCostWithCustomGasLimit",
    values: [BigNumberish, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLastReceivedMessageDetails",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getRouter", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerDestinationChain",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerToken",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "send",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sendWithCustomDestinationGasLimit",
    values: [BigNumberish, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenIds",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateCustodyWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateGasLimit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawToken",
    values: [AddressLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "allowlistSender",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allowlistSourceChain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allowlistedDestinationChains",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allowlistedSenders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allowlistedSourceChains",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ccipReceive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "custodyWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gasLimit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDeliveryFeeCost",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDeliveryFeeCostWithCustomGasLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLastReceivedMessageDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRouter", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerDestinationChain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "send", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sendWithCustomDestinationGasLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenIds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokens", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCustodyWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateGasLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawToken",
    data: BytesLike
  ): Result;
}

export namespace CustodyWalletUpdatedEvent {
  export type InputTuple = [newCustodywallet: AddressLike];
  export type OutputTuple = [newCustodywallet: string];
  export interface OutputObject {
    newCustodywallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GasLimitUpdatedEvent {
  export type InputTuple = [newGasLimit: BigNumberish];
  export type OutputTuple = [newGasLimit: bigint];
  export interface OutputObject {
    newGasLimit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MessageReceivedEvent {
  export type InputTuple = [
    messageId: BytesLike,
    sourceChainSelector: BigNumberish,
    sender: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    receiver: AddressLike
  ];
  export type OutputTuple = [
    messageId: string,
    sourceChainSelector: bigint,
    sender: string,
    token: string,
    amount: bigint,
    receiver: string
  ];
  export interface OutputObject {
    messageId: string;
    sourceChainSelector: bigint;
    sender: string;
    token: string;
    amount: bigint;
    receiver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MessageSentEvent {
  export type InputTuple = [
    messageId: BytesLike,
    destinationChainSelector: BigNumberish,
    receiver: AddressLike,
    tokenId: BigNumberish,
    amount: BigNumberish,
    fees: BigNumberish
  ];
  export type OutputTuple = [
    messageId: string,
    destinationChainSelector: bigint,
    receiver: string,
    tokenId: bigint,
    amount: bigint,
    fees: bigint
  ];
  export interface OutputObject {
    messageId: string;
    destinationChainSelector: bigint;
    receiver: string;
    tokenId: bigint;
    amount: bigint;
    fees: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenRegisteredEvent {
  export type InputTuple = [token: AddressLike, tokenId: BigNumberish];
  export type OutputTuple = [token: string, tokenId: bigint];
  export interface OutputObject {
    token: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BackedCCIPReceiver extends BaseContract {
  connect(runner?: ContractRunner | null): BackedCCIPReceiver;
  waitForDeployment(): Promise<this>;

  interface: BackedCCIPReceiverInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allowlistSender: TypedContractMethod<
    [_sender: AddressLike, _allowed: boolean],
    [void],
    "nonpayable"
  >;

  allowlistSourceChain: TypedContractMethod<
    [_sourceChainSelector: BigNumberish, _allowed: boolean],
    [void],
    "nonpayable"
  >;

  allowlistedDestinationChains: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  allowlistedSenders: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  allowlistedSourceChains: TypedContractMethod<
    [arg0: BigNumberish],
    [boolean],
    "view"
  >;

  ccipReceive: TypedContractMethod<
    [message: Client.Any2EVMMessageStruct],
    [void],
    "nonpayable"
  >;

  custodyWallet: TypedContractMethod<[], [string], "view">;

  gasLimit: TypedContractMethod<[], [bigint], "view">;

  getDeliveryFeeCost: TypedContractMethod<
    [
      _destinationChainSelector: BigNumberish,
      _token: AddressLike,
      _amount: BigNumberish
    ],
    [bigint],
    "view"
  >;

  getDeliveryFeeCostWithCustomGasLimit: TypedContractMethod<
    [
      _destinationChainSelector: BigNumberish,
      _token: AddressLike,
      _amount: BigNumberish,
      _customGasLimit: BigNumberish
    ],
    [bigint],
    "view"
  >;

  getLastReceivedMessageDetails: TypedContractMethod<
    [],
    [
      [string, string, string, bigint] & {
        messageId: string;
        receiver: string;
        token: string;
        amount: bigint;
      }
    ],
    "view"
  >;

  getRouter: TypedContractMethod<[], [string], "view">;

  initialize: TypedContractMethod<
    [_router: AddressLike, _custody: AddressLike, _gasLimit: BigNumberish],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  registerDestinationChain: TypedContractMethod<
    [_destinationChainSelector: BigNumberish, _receiver: AddressLike],
    [void],
    "nonpayable"
  >;

  registerToken: TypedContractMethod<
    [_token: AddressLike, _tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  send: TypedContractMethod<
    [
      _destinationChainSelector: BigNumberish,
      _token: AddressLike,
      _amount: BigNumberish
    ],
    [string],
    "payable"
  >;

  sendWithCustomDestinationGasLimit: TypedContractMethod<
    [
      _destinationChainSelector: BigNumberish,
      _token: AddressLike,
      _amount: BigNumberish,
      _customGasLimit: BigNumberish
    ],
    [string],
    "payable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  tokenIds: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  tokens: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateCustodyWallet: TypedContractMethod<
    [_custody: AddressLike],
    [void],
    "nonpayable"
  >;

  updateGasLimit: TypedContractMethod<
    [_gasLimit: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<
    [_beneficiary: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawToken: TypedContractMethod<
    [_beneficiary: AddressLike, _token: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allowlistSender"
  ): TypedContractMethod<
    [_sender: AddressLike, _allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "allowlistSourceChain"
  ): TypedContractMethod<
    [_sourceChainSelector: BigNumberish, _allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "allowlistedDestinationChains"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "allowlistedSenders"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "allowlistedSourceChains"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "ccipReceive"
  ): TypedContractMethod<
    [message: Client.Any2EVMMessageStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "custodyWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "gasLimit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDeliveryFeeCost"
  ): TypedContractMethod<
    [
      _destinationChainSelector: BigNumberish,
      _token: AddressLike,
      _amount: BigNumberish
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDeliveryFeeCostWithCustomGasLimit"
  ): TypedContractMethod<
    [
      _destinationChainSelector: BigNumberish,
      _token: AddressLike,
      _amount: BigNumberish,
      _customGasLimit: BigNumberish
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLastReceivedMessageDetails"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, bigint] & {
        messageId: string;
        receiver: string;
        token: string;
        amount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRouter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [_router: AddressLike, _custody: AddressLike, _gasLimit: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerDestinationChain"
  ): TypedContractMethod<
    [_destinationChainSelector: BigNumberish, _receiver: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerToken"
  ): TypedContractMethod<
    [_token: AddressLike, _tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "send"
  ): TypedContractMethod<
    [
      _destinationChainSelector: BigNumberish,
      _token: AddressLike,
      _amount: BigNumberish
    ],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "sendWithCustomDestinationGasLimit"
  ): TypedContractMethod<
    [
      _destinationChainSelector: BigNumberish,
      _token: AddressLike,
      _amount: BigNumberish,
      _customGasLimit: BigNumberish
    ],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "tokenIds"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "tokens"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateCustodyWallet"
  ): TypedContractMethod<[_custody: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateGasLimit"
  ): TypedContractMethod<[_gasLimit: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[_beneficiary: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawToken"
  ): TypedContractMethod<
    [_beneficiary: AddressLike, _token: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CustodyWalletUpdated"
  ): TypedContractEvent<
    CustodyWalletUpdatedEvent.InputTuple,
    CustodyWalletUpdatedEvent.OutputTuple,
    CustodyWalletUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "GasLimitUpdated"
  ): TypedContractEvent<
    GasLimitUpdatedEvent.InputTuple,
    GasLimitUpdatedEvent.OutputTuple,
    GasLimitUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "MessageReceived"
  ): TypedContractEvent<
    MessageReceivedEvent.InputTuple,
    MessageReceivedEvent.OutputTuple,
    MessageReceivedEvent.OutputObject
  >;
  getEvent(
    key: "MessageSent"
  ): TypedContractEvent<
    MessageSentEvent.InputTuple,
    MessageSentEvent.OutputTuple,
    MessageSentEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TokenRegistered"
  ): TypedContractEvent<
    TokenRegisteredEvent.InputTuple,
    TokenRegisteredEvent.OutputTuple,
    TokenRegisteredEvent.OutputObject
  >;

  filters: {
    "CustodyWalletUpdated(address)": TypedContractEvent<
      CustodyWalletUpdatedEvent.InputTuple,
      CustodyWalletUpdatedEvent.OutputTuple,
      CustodyWalletUpdatedEvent.OutputObject
    >;
    CustodyWalletUpdated: TypedContractEvent<
      CustodyWalletUpdatedEvent.InputTuple,
      CustodyWalletUpdatedEvent.OutputTuple,
      CustodyWalletUpdatedEvent.OutputObject
    >;

    "GasLimitUpdated(uint256)": TypedContractEvent<
      GasLimitUpdatedEvent.InputTuple,
      GasLimitUpdatedEvent.OutputTuple,
      GasLimitUpdatedEvent.OutputObject
    >;
    GasLimitUpdated: TypedContractEvent<
      GasLimitUpdatedEvent.InputTuple,
      GasLimitUpdatedEvent.OutputTuple,
      GasLimitUpdatedEvent.OutputObject
    >;

    "Initialized(uint8)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "MessageReceived(bytes32,uint64,address,address,uint256,address)": TypedContractEvent<
      MessageReceivedEvent.InputTuple,
      MessageReceivedEvent.OutputTuple,
      MessageReceivedEvent.OutputObject
    >;
    MessageReceived: TypedContractEvent<
      MessageReceivedEvent.InputTuple,
      MessageReceivedEvent.OutputTuple,
      MessageReceivedEvent.OutputObject
    >;

    "MessageSent(bytes32,uint64,address,uint64,uint256,uint256)": TypedContractEvent<
      MessageSentEvent.InputTuple,
      MessageSentEvent.OutputTuple,
      MessageSentEvent.OutputObject
    >;
    MessageSent: TypedContractEvent<
      MessageSentEvent.InputTuple,
      MessageSentEvent.OutputTuple,
      MessageSentEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TokenRegistered(address,uint64)": TypedContractEvent<
      TokenRegisteredEvent.InputTuple,
      TokenRegisteredEvent.OutputTuple,
      TokenRegisteredEvent.OutputObject
    >;
    TokenRegistered: TypedContractEvent<
      TokenRegisteredEvent.InputTuple,
      TokenRegisteredEvent.OutputTuple,
      TokenRegisteredEvent.OutputObject
    >;
  };
}
